/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.konnekting.suite;

import de.konnekting.suite.uicomponents.AutoCompleteTextFieldAddon;
import de.konnekting.suite.utils.Utils;
import de.konnekting.xml.konnektingdevice.v0.CommObjectConfiguration;
import de.root1.knxprojparser.GroupAddress;
import de.root1.knxprojparser.KnxProjParser;
import de.root1.knxprojparser.Project;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Collections;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import de.root1.rooteventbus.RootEventBus;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author achristian
 */
public class GroupAddressInputDialog extends javax.swing.JDialog {

    private CommObjectConfiguration conf;
    private Project knxProject;
    private JFrame frame;

    /**
     * Creates new form GroupAddressInputDialog
     */
    public GroupAddressInputDialog(java.awt.Frame parent) {
        super(parent, true);
        this.frame = frame;
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                closeButton.doClick();
            }

        });

        groupAddressInput.getDocument().addDocumentListener(new DocumentListener() {

            public void inputCompletion() {

            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                associateButton.setEnabled(groupAddressInput.isInputValid());
                inputCompletion();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                associateButton.setEnabled(groupAddressInput.isInputValid());
                inputCompletion();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                associateButton.setEnabled(groupAddressInput.isInputValid());
                inputCompletion();
            }
        });

        knxProject = RootEventBus.getDefault().getStickyEvent(Project.class);
        AutoCompleteTextFieldAddon actfa = new AutoCompleteTextFieldAddon(groupAddressInput, knxProject.getGroupaddressList());
        actfa.setValueComparer(new AutoCompleteTextFieldAddon.AutoCompleteCompare<GroupAddress>() {
            @Override
            public boolean match(String input, GroupAddress value) {
                return value.getAddress().contains(input) || value.getName().contains(input);
            }
        });
        actfa.setValueRenderer(new AutoCompleteTextFieldAddon.AutoCompleteValueRenderer<GroupAddress>() {
            @Override
            public String renderSuggestion(GroupAddress value) {
                return value.getAddress() + "  -  " + value.getName();
            }

            @Override
            public String renderSelectionResult(GroupAddress value) {
                return value.getAddress();
            }
        }
        );
        
        actfa.setActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getRootPane().setDefaultButton(associateButton);
                associateButton.requestFocus();
            }
        });
    }

    private void updateButtons() {
        removeButton.setEnabled(!conf.getGroupAddress().isEmpty());
    }

    public void setCommObjectConfig(CommObjectConfiguration conf) {
        this.conf = conf;
        Collections.sort(conf.getGroupAddress());
        gaList.setListData(conf.getGroupAddress().toArray());
        updateButtons();
    }

    public CommObjectConfiguration getCommObjectConfig() {
        return conf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        associateButton = new javax.swing.JButton();
        groupAddressInput = new de.konnekting.suite.uicomponents.GroupAddressTextField();
        openListButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gaList = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/konnekting/suite/i18n/language"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("GroupAddressInputDialog.borderTitle.addGA"))); // NOI18N

        associateButton.setText(bundle.getString("GroupAddressInputDialog.button.associate")); // NOI18N
        associateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associateButtonActionPerformed(evt);
            }
        });

        groupAddressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupAddressInputActionPerformed(evt);
            }
        });

        openListButton.setText(bundle.getString("GroupAddressInputDialog.button.openList")); // NOI18N
        openListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupAddressInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(associateButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associateButton)
                    .addComponent(groupAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openListButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("GroupAddressInputDialog.borderTitle.associatedGA"))); // NOI18N

        gaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        gaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(gaList);

        removeButton.setText(bundle.getString("GroupAddressInputDialog.button.remove")); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(removeButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addContainerGap())
        );

        closeButton.setText(bundle.getString("GroupAddressInputDialog.button.close")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 260, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (conf != null) {
            List selectedForRemove = gaList.getSelectedValuesList();
            conf.getGroupAddress().removeAll(selectedForRemove);
            gaList.setListData(conf.getGroupAddress().toArray());
            updateButtons();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void associateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associateButtonActionPerformed
        if (conf != null) {
            conf.getGroupAddress().add(groupAddressInput.getText());
            Utils.removeDuplicates(conf.getGroupAddress());
            Collections.sort(conf.getGroupAddress());
            gaList.setListData(conf.getGroupAddress().toArray());
            groupAddressInput.setText(""); // clear input
            groupAddressInput.requestFocus(); // switch focus back to input
            updateButtons();
        }
    }//GEN-LAST:event_associateButtonActionPerformed

    private void groupAddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupAddressInputActionPerformed
        associateButton.doClick();
    }//GEN-LAST:event_groupAddressInputActionPerformed

    private void openListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openListButtonActionPerformed
        GroupAddressListDialog dialog = new GroupAddressListDialog(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_openListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupAddressInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupAddressInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupAddressInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupAddressInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        KnxProjParser parser = new KnxProjParser();
        parser.parse(new java.io.File("/home/achristian/bigdisk/Programming/Arduino/KONNEKTING/KonnektingSampleProjectFolder/KnxProjParser-ExampleProject.knxproj"));
        RootEventBus.getDefault().postSticky(parser.getProject());

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GroupAddressInputDialog dialog = new GroupAddressInputDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton associateButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JList gaList;
    private de.konnekting.suite.uicomponents.GroupAddressTextField groupAddressInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openListButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables

    void setInput(GroupAddress groupAddress) {
        groupAddressInput.setText(groupAddress.getAddress());
        associateButton.requestFocus();
    }
}
