/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.konnekting.suite;

import de.konnekting.deviceconfig.DeviceConfigContainer;
import de.konnekting.deviceconfig.exception.XMLFormatException;
import java.awt.Frame;
import java.util.HashSet;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author achristian
 */
public class ProjectSaver extends javax.swing.JDialog {

    private Logger log = LoggerFactory.getLogger(getClass());
    private final Set<DeviceConfigContainer> devices = new HashSet<>();

    private long lastUserInteraction = System.currentTimeMillis();
    
    private final Frame parentwindow;
    
    private static final long IDLE_SAVE_DELAY = 10 * 60 * 1000; // 10min
    
    private final BackgroundTask saveTask = new BackgroundTask("Save project") {
        @Override
        public void run() {
            synchronized (devices) {
                if (devices.isEmpty()) {
                    done();
                    return;
                }
                updateDialogLocation();
                
                onProgress(0, devices.size(), "");
                validate();

                int i = 0;

                log.info("saving: {}", devices.size());

                for (DeviceConfigContainer device : devices) {
                    log.info("Saving: {}", device);
                    i++;
                    try {

                        String description = device.getIndividualAddress() + " - " + device.getDescription();

                        if (description == null || description.length() == 0) {
                            description = device.getDeviceName() + " [" + device.getManufacturerName() + "]";
                        }

                        onProgress(i, devices.size(), description);
                        device.writeConfig();
                    } catch (XMLFormatException ex) {
                        ex.printStackTrace();
                    } finally {
                        log.info("Saving: {} *done*", device);
                    }
                }
                log.info("save done");

                // finish with empty list
                devices.clear();
            }
            done();
        }
    };
    
    private void updateDialogLocation() {
        setLocationRelativeTo(parentwindow);
    }

    /**
     * Creates new form ProjectSaver
     */
    public ProjectSaver(java.awt.Frame parent) {
        super(parent, true);
        this.parentwindow = parent;
        setUndecorated(true);
        
        initComponents();
        

        Thread t = new Thread("AutoSave") {
            @Override
            public void run() {
                
                while (true) {
                    if (System.currentTimeMillis() - lastUserInteraction > IDLE_SAVE_DELAY) {
                        boolean doSave = false;
                        synchronized(devices) {
                            doSave = !devices.isEmpty();
                        }
                        if (doSave) {
                            save();
                        }
                        lastUserInteraction = System.currentTimeMillis();
                    }
                    try {
                        Thread.currentThread().sleep(1000);
                    } catch (InterruptedException ex) {
                        interrupt();
                    }
                }
            }

        };
        t.setDaemon(true);
        t.start();
    }

    /**
     * Triggers project save of all "dirty" devices. UI with progressdialog will
     * show up and disappear once saved. Can be triggered multiple times.
     */
    public void save() {
        BackgroundTask.runTask(saveTask);
        setVisible(true);
    }

    public void tellUserInteraction() {
        lastUserInteraction = System.currentTimeMillis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressbar = new javax.swing.JProgressBar();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/konnekting/suite/i18n/language"); // NOI18N
        messageLabel.setText(bundle.getString("ProjectSaver.messageLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables

    public void onProgress(int i, int max, String msg) {
        progressbar.setMaximum(max);
        progressbar.setValue(i);
        progressbar.setString(msg);
        progressbar.setStringPainted(true);
    }

    private void done() {
        setVisible(false);
        onProgress(0, 0, "");
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                dispose();
//            }
//        });
    }

    void add(DeviceConfigContainer deviceConfig) {
        log.info("Added dirty: {} -> {}", deviceConfig, deviceConfig.hashCode());
        synchronized (devices) {
            devices.add(deviceConfig);
        }
    }

    void remove(DeviceConfigContainer deviceConfig) {
        log.info("Removed dirty: {} -> {}", deviceConfig, deviceConfig.hashCode());
        synchronized (devices) {
            devices.remove(deviceConfig);
        }
    }

}
