/*
 * Copyright (C) 2016 Alexander Christian <alex(at)root1.de>. All rights reserved.
 * 
 * This file is part of KONNEKTING Suite.
 *
 *   KONNEKTING Suite is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   KONNEKTING Suite is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with KONNEKTING DeviceConfig.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.konnekting.suite;

import de.konnekting.suite.events.EventSaveSettings;
import de.root1.rooteventbus.RootEventBus;
import java.awt.Component;
import java.util.Properties;
import javax.swing.JComponent;

/**
 *
 * @author achristian
 */
public class SettingsDialog extends javax.swing.JDialog {

    private final Properties p = Main.getProperties();
    
    public static final String ACCESS_ROUTING = "ROUTING";
    public static final String ACCESS_TUNNELING = "TUNNELING";
    public static final String ACCESS_TPUART = "TPUART";
    
    public static final String PROP_STARTUP_LASTFOLDER = "startup.lastfolder";
    public static final String PROP_STARTUP_ASKFOLDER = "startup.askfolder";
    
    public static final String PROP_ACCESS = "knx.access";
    public static final String PROP_ROUTING_MULTICASTIP = "knx.routing.multicast";
    public static final String PROP_TUNNELING_IP = "knx.tunneling.ip";
    public static final String PROP_TPUART_DEVICE = "knx.tpuart.device";
    public static final String PROP_INDIVIDUALADDRESS = "knx.individualaddress";

    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        
        boolean lastFolder = Boolean.parseBoolean(p.getProperty(PROP_STARTUP_LASTFOLDER, "false"));
        boolean askFolder = Boolean.parseBoolean(p.getProperty(PROP_STARTUP_ASKFOLDER, "true"));
        
        String access = p.getProperty(PROP_ACCESS, ACCESS_ROUTING);
        String routingMulticast = p.getProperty(PROP_ROUTING_MULTICASTIP, "224.0.23.12");
        String tunnelingIp = p.getProperty(PROP_TUNNELING_IP, "192.168.0.100");
        String tpuartDevice = p.getProperty(PROP_TPUART_DEVICE, "COM3");
        String individualAddress = p.getProperty(PROP_INDIVIDUALADDRESS, "1.0.254");
        
        
        switch(access.toUpperCase()) {
            case ACCESS_ROUTING:
                ipRouterRadioButton.setSelected(true);
                break;
            case ACCESS_TUNNELING:
                ipInterfaceRadioButton.setSelected(true);
                break;
            case ACCESS_TPUART:
                tpuartRadioButton.setSelected(true);
                break;
        }
        
        ipRouterMulticasttextField.setText(routingMulticast);
        ipInterfaceIpTextField.setText(tunnelingIp);
        tpuartDevicetextField.setText(tpuartDevice);
        
        individualAddressTextField.setText(individualAddress);
        
        setEnableAll(ipRouterPanel, ipRouterRadioButton.isSelected());
        setEnableAll(ipInterfacePanel, ipInterfaceRadioButton.isSelected());
        setEnableAll(tpuartPanel, tpuartRadioButton.isSelected());
        
        askFolderCheckbox.setSelected(askFolder);
        lastFolderCheckbox.setSelected(lastFolder);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        settingsTabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        lastFolderCheckbox = new javax.swing.JCheckBox();
        askFolderCheckbox = new javax.swing.JCheckBox();
        knxPanel = new javax.swing.JPanel();
        ipRouterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ipRouterMulticasttextField = new javax.swing.JTextField();
        ipRouterRadioButton = new javax.swing.JRadioButton();
        ipInterfaceRadioButton = new javax.swing.JRadioButton();
        ipInterfacePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ipInterfaceIpTextField = new javax.swing.JTextField();
        tpuartRadioButton = new javax.swing.JRadioButton();
        tpuartPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tpuartDevicetextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        individualAddressTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        settingsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        settingsTabbedPane.setToolTipText("");

        lastFolderCheckbox.setText("Letzten Projektordner automatisch öffnen?");
        lastFolderCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFolderCheckboxActionPerformed(evt);
            }
        });

        askFolderCheckbox.setText("Beim Start nach Projektordner fragen?");
        askFolderCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askFolderCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastFolderCheckbox)
                    .addComponent(askFolderCheckbox))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastFolderCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(askFolderCheckbox)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("Allgemein", generalPanel);

        ipRouterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Multicast IP");

        ipRouterMulticasttextField.setEditable(false);
        ipRouterMulticasttextField.setText("224.0.23.12");
        ipRouterMulticasttextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipRouterMulticasttextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ipRouterPanelLayout = new javax.swing.GroupLayout(ipRouterPanel);
        ipRouterPanel.setLayout(ipRouterPanelLayout);
        ipRouterPanelLayout.setHorizontalGroup(
            ipRouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipRouterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipRouterMulticasttextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ipRouterPanelLayout.setVerticalGroup(
            ipRouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipRouterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ipRouterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ipRouterMulticasttextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(ipRouterRadioButton);
        ipRouterRadioButton.setSelected(true);
        ipRouterRadioButton.setText("IP Router");
        ipRouterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipRouterRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(ipInterfaceRadioButton);
        ipInterfaceRadioButton.setText("IP Interface");
        ipInterfaceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipInterfaceRadioButtonActionPerformed(evt);
            }
        });

        ipInterfacePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("IP-Addresse");

        ipInterfaceIpTextField.setText("192.168.0.100");
        ipInterfaceIpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipInterfaceIpTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ipInterfacePanelLayout = new javax.swing.GroupLayout(ipInterfacePanel);
        ipInterfacePanel.setLayout(ipInterfacePanelLayout);
        ipInterfacePanelLayout.setHorizontalGroup(
            ipInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipInterfacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipInterfaceIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ipInterfacePanelLayout.setVerticalGroup(
            ipInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipInterfacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ipInterfacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ipInterfaceIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(tpuartRadioButton);
        tpuartRadioButton.setText("TPUART via RS232");
        tpuartRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpuartRadioButtonActionPerformed(evt);
            }
        });

        tpuartPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Schnittstelle");

        tpuartDevicetextField.setText("COM3");
        tpuartDevicetextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpuartDevicetextFieldActionPerformed(evt);
            }
        });
        tpuartDevicetextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tpuartDevicetextFieldPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout tpuartPanelLayout = new javax.swing.GroupLayout(tpuartPanel);
        tpuartPanel.setLayout(tpuartPanelLayout);
        tpuartPanelLayout.setHorizontalGroup(
            tpuartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpuartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpuartDevicetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tpuartPanelLayout.setVerticalGroup(
            tpuartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpuartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpuartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tpuartDevicetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Physikalische Adresse KNX");

        individualAddressTextField.setText("1.0.255");
        individualAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualAddressTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("!!!ÄNDERUNGEN WERDEN ERST MIT EINEM NEUSTART DER SUITE WIRKSAM!!!");

        javax.swing.GroupLayout knxPanelLayout = new javax.swing.GroupLayout(knxPanel);
        knxPanel.setLayout(knxPanelLayout);
        knxPanelLayout.setHorizontalGroup(
            knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(knxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(knxPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipRouterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ipInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpuartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(knxPanelLayout.createSequentialGroup()
                        .addGroup(knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipRouterRadioButton)
                            .addComponent(ipInterfaceRadioButton)
                            .addComponent(tpuartRadioButton)
                            .addGroup(knxPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(individualAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        knxPanelLayout.setVerticalGroup(
            knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(knxPanelLayout.createSequentialGroup()
                .addComponent(ipRouterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipRouterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipInterfaceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipInterfacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpuartRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpuartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(knxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(individualAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("KNX", knxPanel);

        saveButton.setText("Übernehmen");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsTabbedPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastFolderCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFolderCheckboxActionPerformed
        updateOpenCheckboxes();
    }//GEN-LAST:event_lastFolderCheckboxActionPerformed

    private void setEnableAll(JComponent c, boolean enabled) {
        c.setEnabled(enabled);
        Component[] components = c.getComponents();
        for (Component component : components) {
            component.setEnabled(enabled);
        }
    }
    
    private void tpuartRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpuartRadioButtonActionPerformed
        setEnableAll(ipRouterPanel, false);
        setEnableAll(ipInterfacePanel, false);
        setEnableAll(tpuartPanel, true);
        p.setProperty(PROP_ACCESS, ACCESS_TPUART);
    }//GEN-LAST:event_tpuartRadioButtonActionPerformed

    private void tpuartDevicetextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpuartDevicetextFieldActionPerformed
        
    }//GEN-LAST:event_tpuartDevicetextFieldActionPerformed

    private void ipInterfaceIpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipInterfaceIpTextFieldActionPerformed
    }//GEN-LAST:event_ipInterfaceIpTextFieldActionPerformed

    private void individualAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualAddressTextFieldActionPerformed
    }//GEN-LAST:event_individualAddressTextFieldActionPerformed

    private void ipInterfaceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipInterfaceRadioButtonActionPerformed
        setEnableAll(ipRouterPanel, false);
        setEnableAll(ipInterfacePanel, true);
        setEnableAll(tpuartPanel, false);
        p.setProperty(PROP_ACCESS, ACCESS_TUNNELING);
    }//GEN-LAST:event_ipInterfaceRadioButtonActionPerformed

    private void ipRouterRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipRouterRadioButtonActionPerformed
        setEnableAll(ipRouterPanel, true);
        setEnableAll(ipInterfacePanel, false);
        setEnableAll(tpuartPanel, false);
        p.setProperty(PROP_ACCESS, ACCESS_ROUTING);
    }//GEN-LAST:event_ipRouterRadioButtonActionPerformed

    private void ipRouterMulticasttextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipRouterMulticasttextFieldActionPerformed
    }//GEN-LAST:event_ipRouterMulticasttextFieldActionPerformed

    private void tpuartDevicetextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tpuartDevicetextFieldPropertyChange
    }//GEN-LAST:event_tpuartDevicetextFieldPropertyChange

    private void doSave() {
        p.setProperty(PROP_ROUTING_MULTICASTIP, ipRouterMulticasttextField.getText());
        p.setProperty(PROP_TPUART_DEVICE, tpuartDevicetextField.getText());
        p.setProperty(PROP_TUNNELING_IP, ipInterfaceIpTextField.getText());
        p.setProperty(PROP_INDIVIDUALADDRESS, individualAddressTextField.getText());
        
        p.setProperty(PROP_STARTUP_LASTFOLDER, lastFolderCheckbox.isSelected()+"");
        p.setProperty(PROP_STARTUP_ASKFOLDER, askFolderCheckbox.isSelected()+"");
        
        RootEventBus.getDefault().post(new EventSaveSettings());
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        doSave();
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void askFolderCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askFolderCheckboxActionPerformed
        updateOpenCheckboxes();
    }//GEN-LAST:event_askFolderCheckboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox askFolderCheckbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JTextField individualAddressTextField;
    private javax.swing.JTextField ipInterfaceIpTextField;
    private javax.swing.JPanel ipInterfacePanel;
    private javax.swing.JRadioButton ipInterfaceRadioButton;
    private javax.swing.JTextField ipRouterMulticasttextField;
    private javax.swing.JPanel ipRouterPanel;
    private javax.swing.JRadioButton ipRouterRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel knxPanel;
    private javax.swing.JCheckBox lastFolderCheckbox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTabbedPane settingsTabbedPane;
    private javax.swing.JTextField tpuartDevicetextField;
    private javax.swing.JPanel tpuartPanel;
    private javax.swing.JRadioButton tpuartRadioButton;
    // End of variables declaration//GEN-END:variables

    private void updateOpenCheckboxes() {
        if (askFolderCheckbox.isSelected()) {
            lastFolderCheckbox.setEnabled(false);
            lastFolderCheckbox.setSelected(false);
        } else
        if (lastFolderCheckbox.isSelected()) {
            askFolderCheckbox.setEnabled(false);
            askFolderCheckbox.setSelected(false);
        } else {
            askFolderCheckbox.setEnabled(true);
            lastFolderCheckbox.setEnabled(true);
        }
    }
}
